# Trigger the pipeline on pushes to the main branch

trigger:
  - main

# Define the agent pool where the pipeline will run
# You can use 'ubuntu-latest', 'windows-latest', or 'macos-latest'
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x' # Specify the Node.js version suitable for your project
  displayName: 'Install Node.js'
- task: BrowserStackConfig@0
  inputs:
    BrowserStackServiceEndPoint: 'Browserstack'
- script: |
    export BROWSERSTACK_USERNAME=$(BROWSERSTACK_USERNAME)
    export BROWSERSTACK_ACCESS_KEY=$(BROWSERSTACK_ACCESS_KEY)
    displayName: 'Setting environment variables'

- script: printenv
  displayName: 'Print all environment variables (Linux)'
  
- script: |
    npm install
  displayName: 'Install Dependencies'

- script: |
    npx browserstack-node-sdk playwright test --config=./playwright.config.js
  displayName: 'Run Playwright Tests on BrowserStack'
  # Set failOnStderr to true if you want the step to fail when any error output is detected
  failOnStderr: true 
