# Azure Pipeline for Playwright tests on BrowserStack (Windows agent)

trigger:
  - main

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x' # Node.js version
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install --save @percy/cli
    npm install @percy/playwright
  displayName: 'Install Dependencies'
- task: BrowserStackConfig@0
  inputs:
    BrowserStackServiceEndPoint: 'Browserstack'
- script: |
    echo "BROWSERSTACK_USERNAME = $env:BROWSERSTACK_USERNAME"
    echo "BROWSERSTACK_ACCESS_KEY = $env:BROWSERSTACK_ACCESS_KEY"
    npm run sample-test 
    # npx percy exec --verbose -- browserstack-node-sdk playwright test --config=./playwright.config.js 
  displayName: 'Run Playwright Tests on BrowserStack'
  failOnStderr: true
